#+TITLE: GnuPG OTP Dot RB

Cutely rhythmic name aside, this script encrypts and decrypts private [[https://gnupg.org/][GnuPG]] keys using the [[https://en.wikipedia.org/wiki/One-time_pad][one-time pad]] (OTP) method.  In this case, a selected OTP (such as [[http://www.gutenberg.org/][a passage from a book]] which is as long or longer than the private key to be encrypted) is used to apply a character-wise offset to a private key, producing a dummy key which is safe for remote backup.

The dummy keys produced by encrypting private keys with this method resemble valid private keys since they are both encoded using the OpenPGP Message Format (see [[https://tools.ietf.org/html/rfc4880#section-6.3][section 6.3 of RFC 4880]]) and have GnuPG headers and footers.  Since each character in a dummy key results from offsetting the character at the same index of a private key by an amount equal to the value of the character at that location in the OTP, dummy keys cannot be decrypted without learning the OTP.  Restoring a lost private key nevertheless remains practical since decryption only requires that one recall the passage of text used as an OTP.

* Usage

- =gnupg-otp.rb encrypt <private key> <one time pad>= \to =<dummy key>= :: Produce a dummy key from a private key and a one time pad.
- =gnupg-otp.rb decrypt <dummy key> <one time pad>= \to =<private key>= :: Recover a private key from a dummy key and a one time pad.
